# Generated by Django 4.0.5 on 2023-04-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_rename_bio_userprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='company_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
